service: serverless-application-offline

custom:
  serverless-offline:
    port: 5001

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: default
  memorySize: 256
  stage: dev

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/persona/buscar
          method: get
          cors: true
      - http:
          path: /api/persona/buscar/{idPersona}
          method: get
          cors: true

plugins:
  - serverless-offline